# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Logger
        run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout release branch code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm install --legacy-peer-deps

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
